import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "@/other/UserProvider";
import { Toaster } from "sonner";
import { ChatProvider } from "@/other/ChatProvider";
import ResponsiveOverlay from "@/components/overlay/ResponsiveOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider 
          attribute="class" 
          enableSystem
          defaultTheme="system" 
        >
          <UserProvider>
            <ChatProvider>
              <ResponsiveOverlay />
              {children}
              <Toaster richColors position='top-right' />
            </ChatProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
